CREATE TABLE syc_orders (
    id VARCHAR(24) PRIMARY KEY,
    order_number VARCHAR(20) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    modified_on TIMESTAMP NOT NULL,
    channel VARCHAR(20),
    testmode BOOLEAN,
    customer_email VARCHAR(255),
    billing_first_name VARCHAR(50),
    billing_last_name VARCHAR(50),
    billing_address1 VARCHAR(255),
    billing_address2 VARCHAR(255),
    billing_city VARCHAR(100),
    billing_state VARCHAR(20),
    billing_country_code VARCHAR(20),
    billing_postal_code VARCHAR(20),
    billing_phone VARCHAR(20),
    fulfillment_status VARCHAR(20),
    line_item_id VARCHAR(24),
    variant_id VARCHAR(36),
    variant_options JSONB,
    sku VARCHAR(20),
    product_id VARCHAR(24),
    product_name VARCHAR(255),
    quantity INT,
    unit_price_paid DECIMAL(10, 2),
    image_url VARCHAR(255),
    line_item_type VARCHAR(20),
    customizations JSONB,
    subtotal DECIMAL(10, 2),
    shipping_total DECIMAL(10, 2),
    discount_total DECIMAL(10, 2),
    tax_total DECIMAL(10, 2),
    refunded_total DECIMAL(10, 2),
    grand_total DECIMAL(10, 2),
    channel_name VARCHAR(50),
    external_order_reference VARCHAR(50),
    fulfilled_on TIMESTAMP,
    price_tax_interpretation VARCHAR(20)
);
